### ISSUE TITLE
API를 통해서 스토어드 프로시져 결과를 받는 방법에 대하여...

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleDBHub_APIServer#3]
```sql
procedure sp_test(in_param in varchar2, out_param1 out int, out_param2 out varchar2) 
is
begin
     if in_param is null then
              out_param1 := -1;
              out_param2 := 'value is null';
       else
              out_param1 := 0;
              out_param2 := 'such';
       end if;
end;
```

올챙이에서..리소스에
call sp_test(?,?,?);

이렇게 사용이 가능할까요?
CallableStatement 생성하고...
registerOutParam....

결과를 어떻게 받을 수 있을지 ...^^;

저장된 리소스가 프로시져 실행인 경우에 파라미터 분석을 해서 in, out여부를 검사하는 작업도 해줘야 하는건지...

**Comment by hangum** [comment]
프로시저는 올챙이에서 프로시저 실행하는 것처럼 해버릴려고 했는데요. 
?? 안을 더 만들어 봐야겠네요.

**Comment by hangum** [comment]
아래의 방법으로 리소스를 정의하시고 실행하세요
https://tadpoledbhub.atlassian.net/wiki/pages/viewpage.action?pageId=23527446
