### ISSUE TITLE
API호출시 리소스 내부에서 두개의 쿼리를 작성한 후에 선택적으로 실행 결과를 받을 수 있을까요?

### ISSUE THREAD

**Issue by jeongjaehong** [hangum/TadpoleDBHub_APIServer#4]
첫번째 인수값에 따라서 실행될 쿼리를 선택하도록 할수 있을까요?

올챙이 리소스 내용에 다음과 같이 작성할 수 있다고 가정.
```javacript
if ( :arg_code = '1' ) {
    SELECT * FROM  user
    WHERE userid = :userid;
} else if (:arg_code = '2') {
    SELECT * FROM  user
    WHERE username like :username ||'%';
} else {
    SELECT * FROM  user
    WHERE status = '1' and  round <= 100;
}
````

또는 아예 특정 인수값을 SQL문의 일부로 치환하는 역활도 가능하면 좋겠네요..
호출시에 ?where=AND ROWNUM <= 100 라고 호출하고 리소스 내용은 아래와 같다면..
```SQL
SELECT * FROM users WHERE userid = :userid $WHERE$;
```
실행시에는 
```SQL
SELECT * FROM users WHERE userid = 'admin' AND ROWNUM <= 100;
```
으로 변환되어 실행이 가능하면 어떤지??
iBatis나 Velocity 처럼...

근데...이런게 보안취약점이 될수도 있겠다는 생각이 갑자기..ㅡㅡ ㅋ
사용자가 직접입력하는 값으로 SQL문장을 조합하는 기능에 사용하면 악의적인 사용에 공격받을 수도 있긴 하겠네요..
사용하기에 따라서....^^;

**Comment by hangum** [comment]
@jeongjaehong  if else 정도의 문법은 필요하겠네요. 
한번 고민해 볼게요.

**Comment by hangum** [comment]
@jeongjaehong  
http://java2s.com/Code/Java/Velocity/IfElseandEnd.htm 

velocity 를 이용해서 처리해야할까 싶어요. 
어때요?

**Comment by hangum** [comment]
Casper로 하니까는 속도가 대략 530 밀리 세컨드 걸리네요.
한번 실행할때마다 0.5초씩이요. 

이렇게까지 잡아 먹어야 하는것인지 고민되네요.

**Comment by hangum** [comment]
Velocity는 120 - 230 밀리 세컨드 걸리고요. 
이정도는 반영해봐도 될까 싶네요.

**Comment by hangum** [comment]
velocity 로 해야겠네요.  
일단 속도가.. 월등해서요.
