### ISSUE TITLE
셈플 코드가 필요합니다. 

### ISSUE THREAD

**Issue by hangum** [hangum/TadpoleDBHub_APIServer#8]
Restful api 테스트 코드가 필요합니다.

자바나 파이썬등의 언어로 코드 테스트 하는 것이요. 
현재는 chrome-extension://hgmloofddffdnphfgcellkdfbfbjeloo/RestClient.html 로 테스트 하는게 다인 상태입니다.
테스트 하시면서 부족한 기능과 추가해야할 것들도 이야기해주시고요.

**Comment by billygoo** [comment]
넵.. 간단히 규칙을 만들고 샘플코드 만들어 볼께요. :)

**Comment by billygoo** [comment]
스크랩: travis-ci.org
빌드 환경 구성을 고려하기: gradle 또는 메이븐

**Comment by hangum** [comment]
^^ 오~ 좋네요

**Comment by billygoo** [comment]
추석 연휴 병원 투어를 하느라 손 되지도 못했네요... 
코드를 어떤 방향으로 만들어야 할지 고민인데....

내부에 테스트 코드를 포함하도록 해야할지?? 아니면 외부에 테스트 코드를 만들어 서비스에 올라간 API를 테스트 해야 할지...?? 

의견 좀 주세요. :)

**Comment by hangum** [comment]
우선은 다른 사용자들이 보고 따라할 셈플코드가 있으면 좋겠어요. 
내부 코드테스트는 제가 해볼게요. 
아직은 많이 지저분해서 리팩토링이 필요할듯해요.

건강은 어때요?

**Comment by billygoo** [comment]
@hangum  아.. 그러면 서비스에 접속해서 Rest API를 리턴받고 검증 하는 코드를 만들어 볼께요.

**Comment by hangum** [comment]
^^ 네.  뭔가 도움이 필요하시면 메시지 주세요.

**Comment by billygoo** [comment]
tadpoledb.com 에서 api 테스트를 하려고 코드를 간단히 만들었는데 timeout 이 나네요... 

혹시 api 주소가 아래와 같이 아이피가 찍히는데 다른데 있는건가요??? 

http://172.31.19.74:8080/tadpoleapi/rest/base/billy/test?value={value_value}

**Comment by billygoo** [comment]
* REF
    * Api 환경설정 : https://tadpoledbhub.atlassian.net/wiki/pages/viewpage.action?pageId=21528844
    * Api Test guide : https://tadpoledbhub.atlassian.net/wiki/display/TADPOLE/API+Test

**Comment by hangum** [comment]
http://54.153.73.132:8080/tadpole/tadpole
이렇구요.

엔진디비 시드비번을 수정해서 코드를 좀 수정해줘야하는데 .. --;; 못한게 방금 생각났어요.
아침까지는 수정해 놓을게요 .--;;


On Mon, Oct 5, 2015 at 12:35 AM, Billy Goo <notifications@github.com> wrote:

> tadpoledb.com 에서 api 테스트를 하려고 코드를 간단히 만들었는데 timeout 이 나네요...
>
> 혹시 api 주소가 아래와 같이 아이피가 찍히는데 다른데 있는건가요???
>
>
> http://172.31.19.74:8080/tadpoleapi/rest/base/billy/test?value={value_value}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hangum/TadpoleDBHub_APIServer/issues/8#issuecomment-145358924>
> .
>



-- 
__________________________
Google Talk: hangum@gmail.com
blog  : http://hangumkj.blogspot.com/
FaceBook : https://www.facebook.com/hangum
Tadpole DB Hub : https://github.com/hangum/TadpoleForDBTools

HyunJong Cho

**Comment by hangum** [comment]
수정했습니다.  해보시고요. 안되시면 메시지 주셔요.

아래의 셈플은 id=102, name 200 을 저장하고 저장한것을 보여주는 셈플입니다. 
http://54.153.73.132:8080/tadpoleapi/rest/base/sample/insertToList?id=102&name=200
TDB_ACCESS_KEY: cd359440-7fa8-432a-8078-494abb057543
TDB_SECRET_KEY: e279e62c-55a6-4c45-8807-0d1247cd401f

**Comment by billygoo** [comment]
https://github.com/billygoo/TadpoleDBHub-ApiTest

올려 놓을곳이 마땅치 않아서... 일단 임시로 레포 생성해서 올렸습니다. 
gradle로 의존성 관리하게 만들어서... 이클립스에서 gradle 설치하시고 사용하시면 됩니다.
junit으로 만들었어요.. 

* 참고 : gradle 이클립스 설치 - http://java.ihoney.pe.kr/300

프로젝트 임포트 후 다음 메뉴를 선택하면 자동으로 라이브러리를 가져와 로컬에 설정합니다. 

> 프로젝트 선택 > 오른쪽 메뉴 > Gradle > Refresh All

그 다음 실행하시면 되요.

**Comment by hangum** [comment]
감사합니다.
